version: 2

updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
  insecure-external-code-execution: allow

- package-ecosystem: "npm"
  directory: "/assets"
  schedule:
    interval: daily
  labels:
    - "dependencies"
  open-pull-requests-limit: 5
