version: "3.7"

services:
  crash:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: crash-dev:latest
    container_name: crash
    working_dir: /app
    command: tail -f /dev/null
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env.dev
    ports:
      - 4000:4000
      - 4369:4369
    volumes:
      - .:/app
      - ./.volumes/crash/_build:/app/_build
      - /var/run/docker.sock:/var/run/docker.sock
