FROM elixir:1.12.3-alpine

MAINTAINER Luca Zulian <contact@lucazulian.it>

RUN apk add --no-cache  \
    nodejs \
    npm \
    inotify-tools

RUN apk add --no-cache \
    postgresql-client \
    curl \
    openssh \
    bash \
    git

RUN mix local.hex --force && mix local.rebar --force

ENV ERL_AFLAGS "-kernel shell_history enabled"

EXPOSE 4369
