version: "3.7"

services:
  crash:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: crash:latest
    container_name: crash
    working_dir: /app
    command: tail -f /dev/null
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env.dev
    ports:
      - 3000:3000
      - 4369:4369
    volumes:
      - .:/app
      - ./.volumes/crash/_build:/app/_build
      - /var/run/docker.sock:/var/run/docker.sock

  crash-node-1:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: crash:latest
    container_name: crash-node-1
    working_dir: /app
    command: tail -f /dev/null
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env.dev
    ports:
      - 3010:3000
      - 4379:4369
    volumes:
      - .:/app
      - ./.volumes/crash/_build:/app/_build
      - /var/run/docker.sock:/var/run/docker.sock

  crash-node-2:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: crash:latest
    container_name: crash-node-2
    working_dir: /app
    command: tail -f /dev/null
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env.dev
    ports:
      - 3020:3000
      - 4389:4369
    volumes:
      - .:/app
      - ./.volumes/crash/_build:/app/_build
      - /var/run/docker.sock:/var/run/docker.sock
